Models/Emp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace FirstMVCDemo.Models
{
    public class Emp
    {
        [Required(ErrorMessage="Id is required")]
        [Display(Name="Emp Id")]
        public int Id { get; set; }
        [Required(ErrorMessage = "name is required")]
        [Display(Name = "Emp Full Name")]
        [MaxLength(40, ErrorMessage = "length should be less than 40 character")]
        [MinLength(2, ErrorMessage = "min legth is 2 character")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress,ErrorMessage="email id is not in proper formmat")]
            public string Email { get; set; }
        [Required(ErrorMessage = "Contact is required")]
        public int Contact { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
       
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FirstMVCDemo.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
    }

}

Models/ErrorViewModel.cs
using System;

namespace FirstMVCDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FirstMVCDemo.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }

    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FirstMVCDemo.Models
{
    public class Student
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public int Percentage { get; set; }
    }
}

Models/Student1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace FirstMVCDemo.Models
{
    public class Student1
    {
        [Required(ErrorMessage = "Rollno is required")]
        [Display(Name = "Student rollno")]
        public int RollNo { get; set; }

        [Required(ErrorMessage = "name is required")]
        [Display(Name = "Emp Full Name")]
        [MaxLength(40, ErrorMessage = "length should be less than 40 character")]
        [MinLength(2, ErrorMessage = "min legth is 2 character")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "Percentage is required")]
        public int Percentage { get; set; }
        [Required(ErrorMessage = "Contact is required")]
        public int Contact { get; set;}
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstMVCDemo.Models;

namespace FirstMVCDemo.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult EmpList()
        {
            List<Employee> empList = new List<Employee>()
            {
                new Employee{Id=1,Name="Rakesh",Salary=34000},
                new Employee{Id=2,Name="Neha",Salary=40000},
                new Employee{Id=3,Name="Sam",Salary=37000},
                new Employee{Id=4,Name="Riya",Salary=20340},
                new Employee{Id=5,Name="Navin",Salary=21000},
                new Employee{Id=6,Name="Ram",Salary=38000},
                new Employee{Id=7,Name="Anil",Salary=65900},
            };
            ViewData["EmpList"] = empList;
            ViewBag.empList = empList;
            return View();
        }
        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddEmployee(Emp emp)
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using FirstMVCDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FirstMVCDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<string> colorList = new List<string>() { "Red","Green","Yellow","Blue","Black","White",
                    "Purple","Pink"};
            ViewData["message"] = "This is my first MVC page";
            ViewData["Experience"] = "I have 2 years of experience";
            ViewData["year"] = 2022;
            ViewData["list"] = colorList;

            ViewBag.ColorList = colorList;
            return View();
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstMVCDemo.Models;

namespace FirstMVCDemo.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            List<Product> products = new List<Product>()
            {
                new Product{Id=1,Name="Dell Laptop",Price=34000},
                new Product{Id=2,Name="Hp Laptop",Price=40000},
                new Product{Id=3,Name="Lenovo Laptop",Price=37000},
                new Product{Id=4,Name="Dell Mouse",Price=340},
                new Product{Id=5,Name="Dell Keyboard",Price=2000},
                new Product{Id=6,Name="RAM",Price=300},
                new Product{Id=7,Name="Hp Mouse",Price=600},
            };
            ViewData["productList"] = products;
            ViewBag.Products = products;
            return View();
        }
        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            return View();
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstMVCDemo.Models;

namespace FirstMVCDemo.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult StudList()
        {
            List<Student> stud = new List<Student>()
            {
                new Student{RollNo=1,Name="Rakesh",Percentage=90},
                new Student{RollNo=2,Name="Neha",Percentage=88},
                new Student{RollNo=3,Name="Sam",Percentage=80},
                new Student{RollNo=4,Name="Riya",Percentage=78},
                new Student{RollNo=5,Name="Navin",Percentage=95},
                new Student{RollNo=6,Name="Ram",Percentage=91},
                new Student{ RollNo=7, Name="Anil",Percentage=65},
            };
            ViewData["StudList"] = stud;
            ViewBag.empList = stud;
            return View();
        }
        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(Student1 student)
        {
            return View();
        }
    }
}

Views/Employee/AddEmployee.cshtml
@model FirstMVCDemo.Models.Emp

@{
    ViewData["Title"] = "AddEmployee";
}

<h1>AddEmployee</h1>

<h4>Emp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEmployee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Employee/EmpList.cshtml
@{
    ViewData["Title"] = "EmpList";
}

<h1>EmpList</h1>

<table class="table table-bordered">
    <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Salary</th>
    </tr>
    @foreach (Employee e in (IEnumerable<Employee>)ViewData["EmpList"])
    {
        <tr>
            <td>@e.Id</td>
            <td>@e.Name</td>
            <td>@e.Salary</td>
        </tr>
     }

</table>
<h1>using ViewBag</h1>

<table class="table table-bordered">
    <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Salary</th>
    </tr>
    @foreach (Employee e in ViewBag.empList)
    {
        <tr>
            <td>@e.Id</td>
            <td>@e.Name</td>
            <td>@e.Salary</td>
        </tr>
    }

</table>

Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
}

<h1>AboutUs</h1>

Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<h1>ContactUs</h1>

 Username:<input type="text" name="username">
 Email id:<input type="text" name="email_id">
<br>
<input type="submit" value="Submit">

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<h3>
    @ViewData["message"]
</h3>
<p>
    @ViewData["Experience"] <small> @ViewData["year"]</small>
</p>
<!-- We are able to write C# code in the cshtml page in the MVC using sign-->
<ol>
    @foreach(string color in(IEnumerable<string>)ViewData["list"])
            {
                <li>
                    @color
                </li>
            }
</ol>
<ul>
    @foreach (var item in ViewBag.ColorList)
    {
        <li>
            @item
        </li>
    }
</ul>

Views/Product/AddProduct.cshtml
@model FirstMVCDemo.Models.Product

@{
    ViewData["Title"] = "AddProduct";
}

<h1>AddProduct</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Views/Product/List.cshtml
@{
    ViewData["Title"] = "List";
}

<h1>Product List</h1>

<table class="table table-bordered">
    <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Price</th>
    </tr>
    @foreach (Product p in (IEnumerable<Product>)ViewData["ProductList"])
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }

</table>
<h1>using ViewBag</h1>

<table class="table table-bordered">
    <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Price</th>
    </tr>
    @foreach (Product p in ViewBag.Products)
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstMVCDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmpList">EmpList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="StudList">StudList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="AddProduct">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="AddEmployee">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="AddEmployee">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="AddStudent">Add Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FirstMVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Student/AddStudent.cshtml
@model FirstMVCDemo.Models.Student1

@{
    ViewData["Title"] = "AddStudent";
}

<h1>AddStudent</h1>

<h4>Student1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddStudent">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RollNo" class="control-label"></label>
                <input asp-for="RollNo" class="form-control" />
                <span asp-validation-for="RollNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Percentage" class="control-label"></label>
                <input asp-for="Percentage" class="form-control" />
                <span asp-validation-for="Percentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Student/StudList.cshtml
@{
    ViewData["Title"] = "StudList";
}

<h1>StudList</h1>
<table class="table table-bordered">
    <tr>
        <th>RollNo</th>
        <th>Name</th>
        <th>Percentage</th>
    </tr>
    @foreach (Student s  in (IEnumerable<Student>)ViewData["StudList"])
    {
        <tr>
            <td>@s.RollNo</td>
            <td>@s.Name</td>
            <td>@s.Percentage</td>
        </tr>
    }

</table>
<h1>using ViewBag</h1>

<table class="table table-bordered">
    <tr>
        <th>RollNo</th>
        <th>Name</th>
        <th>Percentage</th>
    </tr>
    @foreach (Student s in ViewBag.StudList)
    {
        <tr>
            <td>@s.RollNo</td>
            <td>@s.Name</td>
            <td>@s.Percentage</td>
        </tr>
    }

</table>